/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  374: {
    BucketLending: {
      address: "0x2acd323f5a715Af37b9dC0E5e9d79897c9669d8C",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "karmaAddress",
              type: "address",
            },
            {
              internalType: "uint256[]",
              name: "initialBuckets",
              type: "uint256[]",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [],
          name: "CallerNotStealth",
          type: "error",
        },
        {
          inputs: [],
          name: "ECDSAInvalidSignature",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "length",
              type: "uint256",
            },
          ],
          name: "ECDSAInvalidSignatureLength",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "s",
              type: "bytes32",
            },
          ],
          name: "ECDSAInvalidSignatureS",
          type: "error",
        },
        {
          inputs: [],
          name: "ExceedsBorrowLimit",
          type: "error",
        },
        {
          inputs: [],
          name: "InsufficientRepayment",
          type: "error",
        },
        {
          inputs: [],
          name: "InterestTooLow",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidBucket",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidDuration",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidShortString",
          type: "error",
        },
        {
          inputs: [],
          name: "LowKarma",
          type: "error",
        },
        {
          inputs: [],
          name: "NotBorrower",
          type: "error",
        },
        {
          inputs: [],
          name: "NotOverdue",
          type: "error",
        },
        {
          inputs: [],
          name: "NothingToSend",
          type: "error",
        },
        {
          inputs: [],
          name: "PermitAlreadyUsed",
          type: "error",
        },
        {
          inputs: [],
          name: "PermitExpired",
          type: "error",
        },
        {
          inputs: [],
          name: "ReentrancyGuardReentrantCall",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "str",
              type: "string",
            },
          ],
          name: "StringTooLong",
          type: "error",
        },
        {
          inputs: [],
          name: "TransferFailed",
          type: "error",
        },
        {
          inputs: [],
          name: "UnknownLoan",
          type: "error",
        },
        {
          inputs: [],
          name: "WrongStatus",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [],
          name: "EIP712DomainChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "loanId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "lender",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "LenderPaidOut",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "loanId",
              type: "uint256",
            },
          ],
          name: "LoanCancelled",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "loanId",
              type: "uint256",
            },
          ],
          name: "LoanDefaulted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "loanId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "dueTime",
              type: "uint256",
            },
          ],
          name: "LoanFullyFunded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "loanId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "lender",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "totalFunded",
              type: "uint256",
            },
          ],
          name: "LoanFunded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "loanId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "totalRepaid",
              type: "uint256",
            },
          ],
          name: "LoanRepaid",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "loanId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "borrowerStealth",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "bucketAmount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "interestBps",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "duration",
              type: "uint256",
            },
          ],
          name: "LoanRequested",
          type: "event",
        },
        {
          inputs: [],
          name: "INTEREST_DISCOUNT_BPS_PER_KARMA",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "KARMA_BORROW_RATE",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "MIN_INTEREST_BPS",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "MIN_KARMA",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "buckets",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "bucketsList",
          outputs: [
            {
              internalType: "uint256[]",
              name: "",
              type: "uint256[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "loanId",
              type: "uint256",
            },
          ],
          name: "cancelLoan",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "domainSeparator",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "eip712Domain",
          outputs: [
            {
              internalType: "bytes1",
              name: "fields",
              type: "bytes1",
            },
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "string",
              name: "version",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "chainId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "verifyingContract",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "salt",
              type: "bytes32",
            },
            {
              internalType: "uint256[]",
              name: "extensions",
              type: "uint256[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "loanId",
              type: "uint256",
            },
          ],
          name: "fundLoan",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "baseBps",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "karmaBalance",
              type: "uint256",
            },
          ],
          name: "getAdjustedInterestBps",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "loanId",
              type: "uint256",
            },
          ],
          name: "getLenders",
          outputs: [
            {
              internalType: "address[]",
              name: "lenders",
              type: "address[]",
            },
            {
              internalType: "uint256[]",
              name: "amounts",
              type: "uint256[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "loanId",
              type: "uint256",
            },
          ],
          name: "getLoan",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "borrowerStealth",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "bucketAmount",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "interestBps",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "duration",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "fundedAmount",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "fundedAt",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "dueTime",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "createdAt",
                  type: "uint256",
                },
                {
                  internalType: "enum BucketLending.Status",
                  name: "status",
                  type: "uint8",
                },
              ],
              internalType: "struct BucketLending.Loan",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getLoans",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "borrowerStealth",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "bucketAmount",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "interestBps",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "duration",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "fundedAmount",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "fundedAt",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "dueTime",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "createdAt",
                  type: "uint256",
                },
                {
                  internalType: "enum BucketLending.Status",
                  name: "status",
                  type: "uint8",
                },
              ],
              internalType: "struct BucketLending.Loan[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "karmaBalance",
              type: "uint256",
            },
          ],
          name: "getMaxBorrow",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "stealth",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "bucketAmount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "baseInterestBps",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "duration",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "deadline",
              type: "uint256",
            },
            {
              internalType: "bytes32",
              name: "salt",
              type: "bytes32",
            },
          ],
          name: "hashBorrowPermit",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "isValidBucket",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "karma",
          outputs: [
            {
              internalType: "contract IKarma",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "loansCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "loanId",
              type: "uint256",
            },
          ],
          name: "markDefault",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "maxBucket",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          name: "permitUsed",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "loanId",
              type: "uint256",
            },
          ],
          name: "repayLoan",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "stealth",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "bucketAmount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "baseInterestBps",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "duration",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "deadline",
              type: "uint256",
            },
            {
              internalType: "bytes32",
              name: "salt",
              type: "bytes32",
            },
            {
              internalType: "bytes",
              name: "signature",
              type: "bytes",
            },
          ],
          name: "requestLoanWithPermit",
          outputs: [
            {
              internalType: "uint256",
              name: "loanId",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "loanId",
              type: "uint256",
            },
          ],
          name: "totalOwed",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {
        eip712Domain: "@openzeppelin/contracts/utils/cryptography/EIP712.sol",
      },
      deployedOnBlock: 1205000,
    },
    HelloStatusNetwork: {
      address: "0xED6a5C93d576D4A9F66cc2c0b88fDac4A6ed1717",
      abi: [
        {
          inputs: [],
          name: "getGreet",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "greet",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_greet",
              type: "string",
            },
          ],
          name: "setGreet",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 1204998,
    },
    StealthDisperser: {
      address: "0xca45Eb8CF0fB1Ad779148E3fe15820AD0beD375b",
      abi: [
        {
          inputs: [],
          name: "LengthMismatch",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "expected",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "provided",
              type: "uint256",
            },
          ],
          name: "TotalMismatch",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
          ],
          name: "TransferFailed",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "sender",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "recipients",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "total",
              type: "uint256",
            },
          ],
          name: "Dispersed",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "address[]",
              name: "recipients",
              type: "address[]",
            },
            {
              internalType: "uint256[]",
              name: "amounts",
              type: "uint256[]",
            },
          ],
          name: "batch",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 1206039,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
