// Helper: generate packages/nextjs/contracts/deployedContracts.ts from
// compiled artifacts when the `yarn deploy` path isn't available (e.g. you
// don't have a local node running). Uses well-known hardhat deterministic
// addresses. Safe to re-run; the real deploy will overwrite this.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");

const read = rel => JSON.parse(fs.readFileSync(path.join(ROOT, rel), "utf8"));

const contracts = {
  HelloStatusNetwork: {
    address: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
    artifact: "artifacts/contracts/HelloStatusNetwork.sol/HelloStatusNetwork.json",
  },
  Karma: {
    address: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
    artifact: "artifacts/contracts/MockKarma.sol/MockKarma.json",
  },
  BucketLending: {
    address: "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
    artifact: "artifacts/contracts/BucketLending.sol/BucketLending.json",
  },
};

const chainId = 31337;
const entries = {};
for (const [name, { address, artifact }] of Object.entries(contracts)) {
  const json = read(artifact);
  entries[name] = {
    address,
    abi: json.abi,
    inheritedFunctions: {},
    deployedOnBlock: 0,
  };
}

const fileContent = `/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  ${chainId}: ${JSON.stringify(entries, null, 2)},
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
`;

const outPath = path.resolve(ROOT, "../nextjs/contracts/deployedContracts.ts");
fs.writeFileSync(outPath, fileContent);
console.log(`Wrote ${outPath}`);
